import "./globals.css";
import StoreProvider from "./StoreProvider";
import I18nProvider from "./I18nProvider";

export const metadata = {
  title: "Project",
  description: "Generated by ....",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <I18nProvider>
          <StoreProvider>
            {children}
          </StoreProvider>
        </I18nProvider>
      </body>
    </html>
  );
}
