import "./globals.css";
import StoreProvider from "./StoreProvider";
import I18nProvider from "./I18nProvider";
import { ToastProvider } from "@/contexts/ToastContext";

export const metadata = {
  title: "Project",
  description: "Generated by ....",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <StoreProvider>
          <I18nProvider>
            <ToastProvider>
              {children}
            </ToastProvider>
          </I18nProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
